<script setup lang="ts">
import { Key, Plus, WarningFilled } from "@element-plus/icons-vue";
import { onMounted, ref } from "vue"; import { api } from "../lib/request";
const items=ref<any[]>([]), name=ref(""), scopes=ref(["retrieve","chat"]), secret=ref(""), error=ref(""); async function load(){try{items.value=(await api<any>("/api/v1/api-keys")).items}catch(e:any){error.value=e.message}} async function create(){try{const result=await api<any>("/api/v1/api-keys",{method:"POST",body:JSON.stringify({name:name.value,scopes:scopes.value,expires_in_days:90})});secret.value=result.api_key;name.value="";await load()}catch(e:any){error.value=e.message}} async function revoke(item:any){await api(`/api/v1/api-keys/${item.id}`,{method:"DELETE"});await load()} onMounted(load);
</script>
<template>
  <section class="page">
    <div class="page-heading"><div><p class="eyebrow">DEVELOPER ACCESS</p><h2>API Key</h2><p class="page-description">创建专用于应用程序的访问凭证，并精确限制它可以调用的能力。</p></div></div>
    <el-alert v-if="error" :title="error" type="error" class="notice"/>
    <div v-if="secret" class="secret-box"><el-icon><WarningFilled /></el-icon><div><strong>请立即复制此 API Key</strong><p>出于安全原因，它只会在此显示一次。</p><code>{{secret}}</code></div></div>
    <article class="panel"><div class="panel-header"><div><h3 class="panel-title">创建访问凭证</h3><p class="panel-subtitle">默认有效期为 90 天，可按功能选择必要权限。</p></div></div><div class="panel-body"><el-form class="key-form" @submit.prevent="create"><el-form-item label="名称"><el-input v-model="name" placeholder="例如：生产环境服务"/></el-form-item><el-form-item label="权限"><el-checkbox-group v-model="scopes" class="scope-list"><el-checkbox label="retrieve">检索</el-checkbox><el-checkbox label="chat">对话</el-checkbox><el-checkbox label="documents:read">读取文档</el-checkbox><el-checkbox label="documents:write">写入文档</el-checkbox><el-checkbox label="documents:delete">删除文档</el-checkbox></el-checkbox-group></el-form-item><el-button type="primary" native-type="submit"><el-icon><Plus /></el-icon>创建 API Key</el-button></el-form></div></article>
    <article class="panel key-list"><div class="panel-header"><div><h3 class="panel-title">已创建的 Keys</h3><p class="panel-subtitle">请定期轮换未使用或即将过期的访问凭证。</p></div></div><div class="panel-body flush table-wrap"><el-table :data="items"><el-table-column prop="name" label="名称" min-width="190"><template #default="s"><span class="key-name"><el-icon><Key /></el-icon>{{s.row.name}}</span></template></el-table-column><el-table-column prop="key_prefix" label="前缀" min-width="140"><template #default="s"><span class="mono">{{s.row.key_prefix}}</span></template></el-table-column><el-table-column label="权限" min-width="220"><template #default="s"><span class="scope-summary">{{s.row.scopes.join(', ')}}</span></template></el-table-column><el-table-column prop="expires_at" label="过期时间" width="160"/><el-table-column label="操作" width="100"><template #default="s"><el-button link type="danger" @click="revoke(s.row)">吊销</el-button></template></el-table-column></el-table></div></article>
  </section>
</template>
<style scoped>
.secret-box { display: flex; gap: 12px; margin-bottom: 18px; padding: 17px 19px; color: #7d5b10; background: #fff9e9; border: 1px solid #f4df9c; border-radius: 12px; }.secret-box > .el-icon { flex: 0 0 auto; margin-top: 2px; color: #d49a17; font-size: 18px; }.secret-box strong { font-size: 13px; }.secret-box p { margin: 3px 0 8px; color: #997526; font-size: 12px; }.secret-box code { display: inline-block; max-width: 100%; overflow: auto; padding: 7px 9px; color: #704f08; background: rgba(255,255,255,.65); border-radius: 5px; font-family: "DM Mono", monospace; font-size: 11px; }.key-form { display: grid; grid-template-columns: 250px 1fr auto; align-items: end; gap: 14px; }.key-form :deep(.el-form-item) { margin: 0; }.key-form :deep(.el-form-item__label) { padding-bottom: 7px; color: #536075; font-size: 12px; font-weight: 700; line-height: 1.2; }.key-form :deep(.el-button) { height: 38px; }.key-form :deep(.el-button .el-icon) { margin-right: 5px; }.scope-list { display: flex; align-items: center; min-height: 38px; gap: 12px; flex-wrap: wrap; }.scope-list :deep(.el-checkbox) { margin-right: 0; }.key-list { margin-top: 20px; }.key-name { display: inline-flex; align-items: center; gap: 8px; color: #344157; font-weight: 700; }.key-name .el-icon { color: var(--brand); font-size: 16px; }.scope-summary { color: #68758a; font-size: 12px; } @media (max-width: 960px) { .key-form { grid-template-columns: 1fr; }.key-form :deep(.el-button) { width: fit-content; } } @media (max-width: 520px) { .key-form :deep(.el-button) { width: 100%; } }
</style>
