<script setup lang="ts">
import { Plus, UserFilled } from "@element-plus/icons-vue";
import { onMounted, ref } from "vue"; import { api } from "../lib/request";
const items=ref<any[]>([]), email=ref(""), password=ref(""), role=ref("viewer"), error=ref(""); async function load(){try{items.value=(await api<any>("/api/v1/members")).items}catch(e:any){error.value=e.message}} async function add(){try{await api("/api/v1/members",{method:"POST",body:JSON.stringify({mode:"new_user",email:email.value,initial_password:password.value,role:role.value})});email.value="";password.value="";await load()}catch(e:any){error.value=e.message}} async function remove(item:any){await api(`/api/v1/members/${item.id}`,{method:"DELETE"});await load()} onMounted(load);
</script>
<template>
  <section class="page">
    <div class="page-heading"><div><p class="eyebrow">ACCESS CONTROL</p><h2>成员管理</h2><p class="page-description">邀请团队成员，并通过角色控制他们在此租户中的操作范围。</p></div></div>
    <el-alert v-if="error" :title="error" type="error" class="notice"/>
    <article class="panel"><div class="panel-header"><div><h3 class="panel-title">添加成员</h3><p class="panel-subtitle">新用户必须在 24 小时内首次登录并修改密码。</p></div></div><div class="panel-body"><el-form class="member-form" @submit.prevent="add"><el-form-item label="Email"><el-input v-model="email" placeholder="member@company.com"/></el-form-item><el-form-item label="初始密码"><el-input v-model="password" type="password" show-password placeholder="设置临时密码"/></el-form-item><el-form-item label="角色"><el-select v-model="role"><el-option value="tenant_admin" label="Tenant admin"/><el-option value="editor" label="Editor"/><el-option value="viewer" label="Viewer"/></el-select></el-form-item><el-button type="primary" native-type="submit"><el-icon><Plus /></el-icon>创建成员</el-button></el-form></div></article>
    <article class="panel member-list"><div class="panel-header"><div><h3 class="panel-title">租户成员</h3><p class="panel-subtitle">当前拥有此工作区访问权限的成员</p></div><span class="total">{{items.length}} 位成员</span></div><div class="panel-body flush table-wrap"><el-table :data="items"><el-table-column prop="email" label="EMAIL" min-width="270"><template #default="s"><span class="member-email"><span>{{s.row.email.slice(0,1).toUpperCase()}}</span>{{s.row.email}}</span></template></el-table-column><el-table-column prop="role" label="角色" min-width="150"><template #default="s"><el-tag effect="plain" size="small">{{s.row.role}}</el-tag></template></el-table-column><el-table-column prop="status" label="状态" width="140"><template #default="s"><span class="status" :class="s.row.status">{{s.row.status}}</span></template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button link type="danger" @click="remove(s.row)">移除</el-button></template></el-table-column></el-table></div></article>
  </section>
</template>
<style scoped>
.member-form { display: grid; grid-template-columns: 1.3fr 1fr 160px auto; align-items: end; gap: 12px; }.member-form :deep(.el-form-item) { margin: 0; }.member-form :deep(.el-form-item__label) { padding-bottom: 7px; color: #536075; font-size: 12px; font-weight: 700; line-height: 1.2; }.member-form :deep(.el-button) { height: 38px; }.member-form :deep(.el-button .el-icon) { margin-right: 5px; }.member-list { margin-top: 20px; }.total { padding: 5px 9px; color: #6c798e; background: #f5f7fb; border-radius: 6px; font-size: 11px; font-weight: 800; }.member-email { display: inline-flex; align-items: center; gap: 9px; color: #344157; font-weight: 700; }.member-email > span { display: grid; width: 26px; height: 26px; place-items: center; color: var(--brand); background: var(--brand-soft); border-radius: 50%; font-size: 11px; } @media (max-width: 900px) { .member-form { grid-template-columns: 1fr 1fr; }.member-form :deep(.el-button) { width: fit-content; } } @media (max-width: 520px) { .member-form { grid-template-columns: 1fr; }.member-form :deep(.el-button) { width: 100%; } }
</style>
