<script setup lang="ts">
import { ChatDotRound, Document, Search } from "@element-plus/icons-vue";
import { onMounted, ref } from "vue"; import { api } from "../lib/request";
const kbs=ref<any[]>([]), kb=ref(""), query=ref(""), results=ref<any[]>([]), error=ref(""); onMounted(async()=>{kbs.value=(await api<any>("/api/v1/knowledge-bases")).items;kb.value=kbs.value[0]?.id??""}); async function retrieve(){try{results.value=(await api<any>("/api/v1/retrieve",{method:"POST",body:JSON.stringify({knowledge_base_id:kb.value,query:query.value,top_k:5})})).results}catch(e:any){error.value=e.message}}
</script>
<template>
  <section class="page">
    <div class="page-heading"><div><p class="eyebrow">RETRIEVAL LAB</p><h2>检索调试</h2><p class="page-description">在正式接入前，快速检查知识库能否为问题召回正确上下文。</p></div></div>
    <el-alert v-if="error" :title="error" type="error" class="notice"/>
    <article class="panel query-panel"><div class="panel-body"><div class="query-icon"><Search /></div><div class="query-content"><label class="form-label">选择知识库</label><el-select v-model="kb" placeholder="选择一个知识库"><el-option v-for="item in kbs" :key="item.id" :label="item.name" :value="item.id"/></el-select></div><div class="query-content question"><label class="form-label">测试问题</label><el-input v-model="query" placeholder="例如：产品的退款政策是什么？" @keyup.enter="retrieve"/></div><el-button type="primary" :disabled="!kb || !query" @click="retrieve"><el-icon><Search /></el-icon>开始检索</el-button></div></article>
    <div class="result-heading"><div><h3>召回结果</h3><p>{{ results.length ? `找到 ${results.length} 条相关内容` : '输入问题后，相关文档片段将显示在这里' }}</p></div><span v-if="results.length" class="result-count">TOP {{ results.length }}</span></div>
    <div v-if="results.length" class="results"><article v-for="(result, index) in results" :key="result.chunk_id" class="panel result-card"><div class="result-index">{{ String(index + 1).padStart(2, '0') }}</div><div class="panel-body"><div class="result-meta"><span><el-icon><Document /></el-icon>{{result.filename}}</span><span class="distance">距离 {{result.distance}}</span></div><pre>{{result.content}}</pre></div></article></div>
    <div v-else class="empty-state"><span><ChatDotRound /></span><strong>等待你的问题</strong><p>选择知识库并输入问题，查看系统如何定位关联知识。</p></div>
  </section>
</template>
<style scoped>
.query-panel .panel-body { display: flex; align-items: flex-end; gap: 13px; padding: 24px; }.query-icon { display: grid; flex: 0 0 auto; width: 42px; height: 42px; margin-bottom: 1px; place-items: center; color: var(--brand); background: var(--brand-soft); border-radius: 11px; font-size: 20px; }.query-content { width: 210px; }.query-content.question { flex: 1; width: auto; }.query-content :deep(.el-select), .query-content :deep(.el-input) { width: 100%; }.query-panel :deep(.el-button) { height: 38px; }.query-panel :deep(.el-button .el-icon) { margin-right: 5px; }.result-heading { display: flex; align-items: flex-end; justify-content: space-between; margin: 32px 0 14px; }.result-heading h3 { margin: 0 0 5px; font-size: 16px; }.result-heading p { margin: 0; color: var(--muted); font-size: 12px; }.result-count { padding: 5px 9px; color: var(--brand); background: var(--brand-soft); border-radius: 6px; font-size: 11px; font-weight: 800; }.results { display: grid; gap: 12px; }.result-card { position: relative; overflow: visible; }.result-index { position: absolute; top: 20px; left: -12px; display: grid; width: 28px; height: 28px; place-items: center; color: #75829a; background: #f0f3f8; border: 3px solid var(--canvas); border-radius: 50%; font-size: 10px; font-weight: 800; }.result-card .panel-body { padding-left: 30px; }.result-meta { display: flex; align-items: center; justify-content: space-between; gap: 12px; color: #4c5b70; font-size: 12px; font-weight: 700; }.result-meta > span:first-child { display: flex; align-items: center; gap: 7px; }.result-meta .el-icon { color: var(--brand); font-size: 16px; }.distance { padding: 4px 7px; color: #64728a; background: #f5f7fb; border-radius: 5px; font-size: 10px; }.result-card pre { margin: 15px 0 0; color: #506077; font-family: inherit; font-size: 13px; line-height: 1.75; white-space: pre-wrap; }.empty-state { display: grid; min-height: 210px; place-content: center; justify-items: center; color: #8590a2; border: 1px dashed #d9e0eb; border-radius: 16px; background: rgba(255,255,255,.44); }.empty-state > span { display: grid; width: 44px; height: 44px; margin-bottom: 11px; place-items: center; color: #97a4ba; background: #eef2f8; border-radius: 13px; font-size: 21px; }.empty-state strong { color: #5a687d; font-size: 13px; }.empty-state p { margin: 6px 0 0; font-size: 12px; } @media (max-width: 720px) { .query-panel .panel-body { align-items: stretch; flex-wrap: wrap; }.query-icon { display: none; }.query-content, .query-content.question { width: 100%; }.query-panel :deep(.el-button) { width: 100%; } }
</style>
