<script setup lang="ts">
import { OfficeBuilding, Plus } from "@element-plus/icons-vue";
import { onMounted, ref } from "vue"; import { useRouter } from "vue-router"; import { api } from "../lib/request"; import { setTenant } from "../composables/useAuth";
const router=useRouter(); const items=ref<any[]>([]), name=ref(""), error=ref(""); async function load(){try{items.value=(await api<any>("/api/v1/tenants")).items}catch(e:any){error.value=e.message}} async function create(){try{const tenant=await api<any>("/api/v1/tenants",{method:"POST",body:JSON.stringify({name:name.value})});name.value="";setTenant(tenant.id);await router.push("/")}catch(e:any){error.value=e.message}} async function toggle(item:any){await api(`/api/v1/tenants/${item.id}`,{method:"PATCH",body:JSON.stringify({status:item.status==="active"?"disabled":"active"})});await load()} onMounted(load);
</script>
<template>
  <section class="page">
    <div class="page-heading"><div><p class="eyebrow">PLATFORM ADMIN</p><h2>租户管理</h2><p class="page-description">创建、启用或暂停平台租户。新租户创建后会自动切换到该工作区。</p></div></div>
    <el-alert v-if="error" :title="error" type="error" class="notice"/>
    <article class="panel"><div class="panel-header"><div><h3 class="panel-title">新建租户</h3><p class="panel-subtitle">为新的团队或客户开通独立工作区。</p></div></div><div class="panel-body"><el-form class="tenant-form" @submit.prevent="create"><el-form-item label="租户名称"><el-input v-model="name" placeholder="例如：北极星科技"/></el-form-item><el-button type="primary" native-type="submit"><el-icon><Plus /></el-icon>创建并进入租户</el-button></el-form></div></article>
    <article class="panel tenant-list"><div class="panel-header"><div><h3 class="panel-title">所有租户</h3><p class="panel-subtitle">平台中已创建的独立工作区</p></div><span class="total">{{items.length}} 个租户</span></div><div class="panel-body flush table-wrap"><el-table :data="items"><el-table-column prop="name" label="名称" min-width="280"><template #default="s"><span class="tenant-name"><span class="tenant-icon"><el-icon><OfficeBuilding /></el-icon></span>{{s.row.name}}</span></template></el-table-column><el-table-column prop="status" label="状态" width="160"><template #default="s"><span class="status" :class="s.row.status">{{s.row.status === 'active' ? '已启用' : '已停用'}}</span></template></el-table-column><el-table-column label="操作" width="130"><template #default="s"><el-button link :type="s.row.status==='active' ? 'danger' : 'primary'" @click="toggle(s.row)">{{s.row.status==='active'?'停用':'启用'}}</el-button></template></el-table-column></el-table></div></article>
  </section>
</template>
<style scoped>
.tenant-form { display: flex; align-items: end; gap: 12px; }.tenant-form :deep(.el-form-item) { margin: 0; }.tenant-form :deep(.el-form-item__label) { padding-bottom: 7px; color: #536075; font-size: 12px; font-weight: 700; line-height: 1.2; }.tenant-form :deep(.el-input) { width: 300px; }.tenant-form :deep(.el-button) { height: 38px; }.tenant-form :deep(.el-button .el-icon) { margin-right: 5px; }.tenant-list { margin-top: 20px; }.total { padding: 5px 9px; color: #6c798e; background: #f5f7fb; border-radius: 6px; font-size: 11px; font-weight: 800; }.tenant-name { display: inline-flex; align-items: center; gap: 10px; color: #344157; font-weight: 700; }.tenant-icon { display: grid; width: 27px; height: 27px; place-items: center; color: #315efb; background: #edf1ff; border-radius: 7px; }.tenant-icon .el-icon { font-size: 15px; } @media (max-width: 520px) { .tenant-form { display: grid; }.tenant-form :deep(.el-input), .tenant-form :deep(.el-button) { width: 100%; } }
</style>
